// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Papra.Companion.Data;

#nullable disable

namespace Papra.Companion.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417205406_AddPromptFields")]
    partial class AddPromptFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Papra.Companion.Data.Entities.JobResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("JobResults");
                });

            modelBuilder.Entity("Papra.Companion.Data.Entities.PipelineSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MistralApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OcrPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenAiApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenAiModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PapraApiToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PapraBaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitlePrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PipelineSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
